### ISSUE TITLE
problem with install Neuro.

### ISSUE THREAD

**Issue by tigers2020** [kimjammer/Neuro#2]
while I try install with venv pip install -r requirements.txt
 i am getting error of this.

ERROR: deepspeed-0.14.0+cu118-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.
which my computer spec is this.

![image](https://github.com/kimjammer/Neuro/assets/18249934/d7f02859-0d47-4d25-ae8f-a86dad6a6715)
![image](https://github.com/kimjammer/Neuro/assets/18249934/cb6f6a56-7848-4eef-acf6-e20d00d6fe45)

**Comment by kimjammer** [comment]
You'll need to download and install the correct wheel from [here](https://github.com/erew123/alltalk_tts/releases/tag/DeepSpeed-14.0). First, make sure you're on Python 3.11 and have Pytorch 2.2.2 installed with CUDA 11.8 in your venv.

**Comment by kimjammer** [comment]
Alternatively, you can just not use deepspeed by changing use_deepspeed to False in tts.py. But this will make the TTS slower.

```python
engine = CoquiEngine(
            use_deepspeed=False,
            voice="./voices/" + VOICE_REFERENCE,
            speed=1.1,
        )
```

**Comment by KaisuzanAI** [comment]
i havent been able to fix this issue for my side, i got everything else working. but this is the main one i cant seem to figure out

**Comment by kimjammer** [comment]
Hi, could you please list the following? CPU, GPU, OS, virtual environment python version, and virtual environment installed dependencies with `pip list`.

**Comment by tigers2020** [comment]
after try install with pip install -r requrements.txt
![image](https://github.com/kimjammer/Neuro/assets/18249934/e320fef2-00e2-4993-bd6a-54a2fbbfad6c)

CPU : AMD 3950x
GPU: GTX 4090
OS: Windows 11

**Comment by kimjammer** [comment]
Hi, thanks for the info. First, you _need_ to be using python 3.11, or you won't be able to install deepspeed and I can't guarantee that the dependencies won't clash on 3.10. Next, install pytorch first with `pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118`. Then install requirements, and finally install deepspeed. If that works let me know and I'll update the documentation.

**Comment by KaisuzanAI** [comment]
im getting this error:


Error loading model for checkpoint D:\Ai stuff\Kai-Suzaan\models\v2.0.2: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.ERROR:root:Error initializing main coqui engine model: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1510, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 56, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flash_attn\flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeTTS\engines\coqui_engine.py", line 509, in _synthesize_worker
    tts = load_model(checkpoint, tts)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeTTS\engines\coqui_engine.py", line 481, in load_model
    config = load_config((os.path.join(checkpoint, "config.json")))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\config\__init__.py", line 97, in load_config
    config_class = register_config(model_name.lower())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\config\__init__.py", line 40, in register_config
    from TTS.tts.configs.xtts_config import XttsConfig
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\configs\xtts_config.py", line 5, in <module>
    from TTS.tts.models.xtts import XttsArgs, XttsAudioConfig
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\models\xtts.py", line 10, in <module>
    from TTS.tts.layers.xtts.gpt import GPT
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 12, in <module>
    from TTS.tts.layers.xtts.gpt_inference import GPT2InferenceModel
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\layers\xtts\gpt_inference.py", line 5, in <module>
    from transformers import GPT2PreTrainedModel
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1501, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1500, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1512, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.

Process Process-1:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1510, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\gpt2\modeling_gpt2.py", line 56, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flash_attn\__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\flash_attn\flash_attn_interface.py", line 10, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeTTS\engines\coqui_engine.py", line 509, in _synthesize_worker
    tts = load_model(checkpoint, tts)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeTTS\engines\coqui_engine.py", line 481, in load_model
    config = load_config((os.path.join(checkpoint, "config.json")))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\config\__init__.py", line 97, in load_config
    config_class = register_config(model_name.lower())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\config\__init__.py", line 40, in register_config
    from TTS.tts.configs.xtts_config import XttsConfig
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\configs\xtts_config.py", line 5, in <module>
    from TTS.tts.models.xtts import XttsArgs, XttsAudioConfig
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\models\xtts.py", line 10, in <module>
    from TTS.tts.layers.xtts.gpt import GPT
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\layers\xtts\gpt.py", line 12, in <module>
    from TTS.tts.layers.xtts.gpt_inference import GPT2InferenceModel
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\TTS\tts\layers\xtts\gpt_inference.py", line 5, in <module>
    from transformers import GPT2PreTrainedModel
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1501, in __getattr__
    value = getattr(module, name)
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1500, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\utils\import_utils.py", line 1512, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.gpt2.modeling_gpt2 because of the following error (look up to see its traceback):
DLL load failed while importing flash_attn_2_cuda: The specified module could not be found.

**Comment by kimjammer** [comment]
Hi, @KaisuzanAI, could you tell me your CPU, GPU, OS, virtual environment python version, and virtual environment installed dependencies with `pip list`? Thanks. Uninstalling and reinstalling flash_attn pip library may also help.

**Comment by KaisuzanAI** [comment]
cpu: i13th Gen Intel(R) Core(TM) i9-13900K, 3000 Mhz, 24 Core(s), 32 Logical Processor(s)
Gpu: nvidia GTX 4090
OS; Windows 11
python: Python 3.11.0

**Comment by kimjammer** [comment]
Thanks! It looks like you have added a handful of libraries, and some of them are for Cuda 12.1. I'm assuming you have the additional libraries because you've made changes to Neuro? It also looks like your torchaudio library got overridden at some point and is not the Cuda 11.8 version. Because of this, I suspect some of the libraries have gotten confused about where the correct CUDA DLLs are.

I would recommend creating separate new virtual environment and doing a clean install of the current version of Neuro in it and see if the same error still appears. For reference, here is what my current pip list looks like:

<details><summary>pip list</summary>
<p>

absl-py 2.1.0
aiofiles 23.2.1
aiohttp 3.9.3
aiosignal 1.3.1
annotated-types 0.6.0
anyascii 0.3.2
anyio 4.3.0
asttokens 2.4.1
attrs 23.2.0
audioread 3.0.1
av 11.0.0
azure-cognitiveservices-speech 1.36.0
Babel 2.14.0
bangla 0.0.2
bidict 0.23.1
blinker 1.7.0
blis 0.7.11
bnnumerizer 0.0.2
bnunicodenormalizer 0.1.6
catalogue 2.0.10
certifi 2024.2.2
cffi 1.16.0
charset-normalizer 3.3.2
click 8.1.7
cloudpathlib 0.16.0
colorama 0.4.6
coloredlogs 15.0.1
comtypes 1.4.0
confection 0.1.4
contourpy 1.2.1
coqpit 0.0.17
ctranslate2 4.1.0
cycler 0.12.1
cymem 2.0.8
Cython 3.0.10
dateparser 1.1.8
decorator 5.1.1
deepspeed 0.14.0+unknown
distro 1.9.0
docopt 0.6.2
einops 0.7.0
elevenlabs 0.2.27
emoji 2.8.0
encodec 0.1.1
enum34 1.1.10
executing 2.0.1
faster-whisper 1.0.1
filelock 3.9.0
Flask 3.0.3
flatbuffers 24.3.25
fonttools 4.51.0
frozenlist 1.4.1
fsspec 2024.3.1
g2pkk 0.1.2
grpcio 1.62.1
gruut 2.2.3
gruut-ipa 0.13.0
gruut_lang_de 2.0.0
gruut_lang_en 2.0.0
gruut_lang_es 2.0.0
gruut_lang_fr 2.0.2
h11 0.14.0
halo 0.0.31
hangul-romanize 0.1.0
hjson 3.1.0
httpcore 1.0.5
httpx 0.27.0
huggingface-hub 0.22.2
humanfriendly 10.0
idna 3.6
inflect 7.2.0
ipython 8.23.0
itsdangerous 2.1.2
jamo 0.4.1
jedi 0.19.1
jieba 0.42.1
Jinja2 3.1.2
joblib 1.4.0
jsonlines 1.2.0
kiwisolver 1.4.5
langcodes 3.3.0
lazy_loader 0.4
librosa 0.10.1
llvmlite 0.42.0
log-symbols 0.0.14
Markdown 3.6
MarkupSafe 2.1.3
matplotlib 3.8.4
matplotlib-inline 0.1.6
more-itertools 10.2.0
mpmath 1.3.0
msgpack 1.0.8
mss 9.0.1
multidict 6.0.5
murmurhash 1.0.10
networkx 2.8.8
ninja 1.11.1.1
nltk 3.8.1
num2words 0.5.13
numba 0.59.1
numpy 1.26.4
onnxruntime 1.17.1
openai 1.13.3
opencv-python 4.9.0.80
packaging 24.0
pandas 1.5.3
parso 0.8.4
pillow 10.3.0
pip 24.0
platformdirs 4.2.0
pooch 1.8.1
preshed 3.0.9
prompt-toolkit 3.0.43
protobuf 5.26.1
psutil 5.9.8
pure-eval 0.2.2
pvporcupine 1.9.5
py-cord 2.5.0
py-cpuinfo 9.0.0
PyAudio 0.2.14
pycparser 2.22
pydantic 2.6.4
pydantic_core 2.16.3
pydub 0.25.1
Pygments 2.17.2
PyNaCl 1.5.0
pynndescent 0.5.12
pynvml 11.5.0
pyparsing 3.1.2
pypinyin 0.51.0
pypiwin32 223
pyreadline3 3.4.1
pysbd 0.3.4
python-crfsuite 0.9.10
python-dateutil 2.9.0.post0
python-dotenv 1.0.1
python-engineio 4.9.0
python-socketio 5.11.2
pyttsx3 2.90
pytz 2024.1
pyvts 0.3.2
pywin32 306
PyYAML 6.0.1
RealTimeSTT 0.1.13
RealTimeTTS 0.3.44
regex 2023.12.25
requests 2.31.0
safetensors 0.4.2
scikit-learn 1.4.1.post1
scipy 1.13.0
setuptools 65.5.0
simple-websocket 1.0.0
six 1.16.0
smart-open 6.4.0
sniffio 1.3.1
soundfile 0.12.1
soxr 0.3.7
spacy 3.7.4
spacy-legacy 3.0.12
spacy-loggers 1.0.5
spinners 0.0.24
srsly 2.4.8
sseclient-py 1.8.0
stack-data 0.6.3
stanza 1.6.1
stream2sentence 0.2.3
SudachiDict-core 20240109
SudachiPy 0.6.8
sympy 1.12
tensorboard 2.16.2
tensorboard-data-server 0.7.2
termcolor 2.4.0
thinc 8.2.3
threadpoolctl 3.4.0
tokenizers 0.15.2
torch 2.2.2+cu118
torchaudio 2.2.2+cu118
tqdm 4.66.2
trainer 0.0.36
traitlets 5.14.2
transformers 4.39.3
TTS 0.22.0
twitchAPI 4.2.0
typeguard 4.2.1
typer 0.9.4
typing_extensions 4.11.0
tzdata 2024.1
tzlocal 5.2
umap-learn 0.5.6
Unidecode 1.3.8
urllib3 2.2.1
wasabi 1.1.2
wcwidth 0.2.13
weasel 0.3.4
webrtcvad 2.0.10
websockets 12.0
Werkzeug 3.0.2
wsproto 1.2.0
yarl 1.9.4
</p>
</details>

**Comment by KaisuzanAI** [comment]
gotcha thanks! i did manage to get rid of the main errors, all that im now dealing with is this:

```
ERROR:root:Unhandled exeption in _realtime_worker: Library cublas64_12.dll is not found or cannot be loaded
RealTimeSTT: root - ERROR - Unhandled exeption in _realtime_worker: Library cublas64_12.dll is not found or cannot be loaded
Exception in thread Thread-9 (_realtime_worker):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeSTT\audio_recorder.py", line 1302, in _realtime_worker
    self.realtime_transcription_text = " ".join(
                                       ^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeSTT\audio_recorder.py", line 1302, in <genexpr>
    self.realtime_transcription_text = " ".join(
                                               ^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\faster_whisper\transcribe.py", line 511, in generate_segments
    encoder_output = self.encode(segment)
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\faster_whisper\transcribe.py", line 762, in encode
    return self.model.encode(features, to_cpu=to_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
SIGNALS: Human Talking Stop
ERROR:root:General transcription error: Library cublas64_12.dll is not found or cannot be loaded
ERROR:root:Library cublas64_12.dll is not found or cannot be loaded
RealTimeSTT: root - ERROR - Library cublas64_12.dll is not found or cannot be loaded
Exception in thread Thread-3 (listen_loop):
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Ai stuff\Kai-Suzaan\stt.py", line 62, in listen_loop
    recorder.text(self.process_text)
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeSTT\audio_recorder.py", line 891, in text
    args=(self.transcribe(),)).start()
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\RealtimeSTT\audio_recorder.py", line 852, in transcribe
    raise Exception(result)
Exception: Library cublas64_12.dll is not found or cannot be loaded
```

**Comment by kimjammer** [comment]
This is a known (annoying) problem most likely in pytorch 2.2.2. To fix it, go to wherever cubas64_11.dll is ("C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\cublas64_11.dll" for me), make a copy, and rename it to cublas64_12.dll. It sounds very stupid but it works.

**Comment by KaisuzanAI** [comment]
i got it working, but for some reason, the model i was using (a mistral model) wasnt working at all

**Comment by tigers2020** [comment]
I did install torch with your code above.
`pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118`
and install requirement.txt

but always endup problem with deepspeed installation.

`(venv) PS C:\ai\Neuro> pip install deepspeed
Collecting deepspeed
  Using cached deepspeed-0.14.2.tar.gz (1.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      [2024-05-14 19:36:00,531] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      [2024-05-14 19:36:00,878] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
      test.c
      LINK : fatal error LNK1181: 'aio.lib' 입력 파일을 열 수 없습니다.
      [2024-05-14 19:36:03,155] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
      test.c
      LINK : fatal error LNK1181: 'aio.lib' 입력 파일을 열 수 없습니다.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\hyper\AppData\Local\Temp\pip-install-mrrgmb_v\deepspeed_903436a0fcf04dafb8ea95e53990e404\setup.py", line 190, in <module>
          ext_modules.append(builder.builder())
                             ^^^^^^^^^^^^^^^^^
        File "C:\Users\hyper\AppData\Local\Temp\pip-install-mrrgmb_v\deepspeed_903436a0fcf04dafb8ea95e53990e404\op_builder\builder.py", line 634, in builder
          assert_no_cuda_mismatch(self.name)
        File "C:\Users\hyper\AppData\Local\Temp\pip-install-mrrgmb_v\deepspeed_903436a0fcf04dafb8ea95e53990e404\op_builder\builder.py", line 101, in assert_no_cuda_mismatch
          raise CUDAMismatchException(
      op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.4 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
       [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.2
       [WARNING]  please install triton==1.0.0 if you want to use sparse attention
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
(venv) PS C:\ai\Neuro>
`

**Comment by kimjammer** [comment]
Hi, the standard version of deepspeed does not work and you need to use a custom version of deepspeed. You might have missed it in the readme, but in short, use [these wheels](https://github.com/erew123/alltalk_tts/releases/tag/DeepSpeed-14.0) by alltalk_tts. You can read more about the deepspeed installation process [here](https://github.com/erew123/alltalk_tts?#-deepspeed-installation-options), on their readme page. Download the version for Cuda 11.8, and install it with `pip install wheel_filename.whl`. Note that python 3.11 and pytorch 2.2.1/2.2.2 are required.
