### ISSUE TITLE
Access to model meta-llama/Meta-Llama-3-8B is restricted

### ISSUE THREAD

**Issue by tigers2020** [kimjammer/Neuro#6]
of cause I did request access, but never approved for weeks.  I have many other models, can't I use them instead?

```
Traceback (most recent call last):
  File "C:\ai\Neuro\main.py", line 101, in <module>
    asyncio.run(main())
  File "C:\Users\hyper\.pyenv\pyenv-win\versions\3.11.0b4\Lib\asyncio\runners.py", line 187, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\hyper\.pyenv\pyenv-win\versions\3.11.0b4\Lib\asyncio\runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hyper\.pyenv\pyenv-win\versions\3.11.0b4\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ai\Neuro\main.py", line 47, in main
    llm_wrapper = LLMWrapper(signals, tts, modules)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\Neuro\llmWrapper.py", line 35, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(MODEL, token=os.getenv("HF_TOKEN"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\Neuro\venv\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 794, in from_pretrained
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\Neuro\venv\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1138, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\Neuro\venv\Lib\site-packages\transformers\configuration_utils.py", line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\Neuro\venv\Lib\site-packages\transformers\configuration_utils.py", line 686, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "C:\ai\Neuro\venv\Lib\site-packages\transformers\utils\hub.py", line 416, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B.
401 Client Error. (Request ID: Root=1-66440373-2f5733c54ea4b62114e20788;3c5d8e79-6c3e-4382-96b1-fc295646728f)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B/resolve/main/config.json.
Access to model meta-llama/Meta-Llama-3-8B is restricted. You must be authenticated to access it.


```

**Comment by kimjammer** [comment]
Of course, you can load any model you like into text-generation-webui and run it. You may want to remove `"skip_special_tokens": False,` in llmWrapper.py, and you will need to update constants.py. The current system prompt is also designed for Llama 3, so you will probably want to experiment with it.

On the other hand, are you sure you don't have access to Llama 3? They usually grant access within hours. If you log in and can see any files and folders [here](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/tree/main), you have access. Get your huggingface token and put it in the .env file.
